; ──────────────────────────────────────────────
;  Odoo ${ODOO_VERSION} — generated by odoo-autoinstaller
; ──────────────────────────────────────────────

[options]

; === Addons ===
addons_path = ${ODOO_ADDONS_PATH}

; === Security ===
admin_passwd = ${ODOO_ADMIN_PASSWD}

csv_internal_sep = ,
data_dir = ${ODOO_DATA_DIR}
db_host = ${DB_HOST}
db_maxconn = 64
db_maxconn_gevent = False
db_name = ${DB_NAME}
db_password = ${DB_PASSWORD}
db_port = ${DB_PORT}
db_replica_host = False
db_replica_port = False
db_sslmode = prefer
db_template = template0
db_user = ${DB_USER}
dbfilter = 
email_from = False
from_filter = False
geoip_city_db = /usr/share/GeoIP/GeoLite2-City.mmdb
geoip_country_db = /usr/share/GeoIP/GeoLite2-Country.mmdb
gevent_port = 8072
http_enable = True
http_interface = ${ODOO_HTTP_INTERFACE}
http_port = ${ODOO_PORT}
import_partial = 
limit_memory_hard = ${ODOO_LIMIT_MEMORY_HARD}
limit_memory_hard_gevent = False
limit_memory_soft = ${ODOO_LIMIT_MEMORY_SOFT}
limit_memory_soft_gevent = False
limit_request = ${ODOO_LIMIT_REQUEST}
limit_time_cpu = ${ODOO_LIMIT_TIME_CPU}
limit_time_real = ${ODOO_LIMIT_TIME_REAL}
limit_time_real_cron = -1
limit_time_worker_cron = 0
list_db = True
log_db = False
log_db_level = warning
log_handler = :INFO
log_level = ${ODOO_LOG_LEVEL}
logfile = ${ODOO_LOGFILE}
max_cron_threads = ${ODOO_MAX_CRON_THREADS}
osv_memory_count_limit = 0
pg_path = 
pidfile = 
pre_upgrade_scripts = 
proxy_mode = ${ODOO_PROXY_MODE}
reportgz = False
screencasts = 
screenshots = /tmp/odoo_tests
server_wide_modules = base,web
skip_auto_install = False
smtp_password = False
smtp_port = 25
smtp_server = localhost
smtp_ssl = False
smtp_ssl_certificate_filename = False
smtp_ssl_private_key_filename = False
smtp_user = False
syslog = False
test_enable = False
test_file = 
test_tags = None
transient_age_limit = 1.0
translate_modules = ['all']
unaccent = False
upgrade_path = 
websocket_keep_alive_timeout = 3600
websocket_rate_limit_burst = 10
websocket_rate_limit_delay = 0.2
without_demo = False
workers = ${ODOO_WORKERS}
x_sendfile = False
