[options]
; ──────────────────────────────────────────────
;  Odoo ${ODOO_VERSION} — generated by odoo-autoinstaller
;  $(date -u '+%Y-%m-%d %H:%M:%S UTC')
; ──────────────────────────────────────────────

; === Security ===
admin_passwd = ${ODOO_ADMIN_PASSWD}

; === Database ===
db_host     = ${DB_HOST}
db_port     = ${DB_PORT}
db_user     = ${DB_USER}
db_password = ${DB_PASSWORD}
db_name     = ${DB_NAME}

; === HTTP ===
http_interface = ${ODOO_HTTP_INTERFACE}
http_port      = ${ODOO_PORT}
proxy_mode     = ${ODOO_PROXY_MODE}

; === Paths ===
addons_path = ${ODOO_ADDONS_PATH}
data_dir    = ${ODOO_DATA_DIR}
logfile     = ${ODOO_LOGFILE}

; === Workers (0 = multi-thread mode, >0 = multi-process) ===
workers             = ${ODOO_WORKERS}
max_cron_threads    = ${ODOO_MAX_CRON_THREADS}

; === Limits ===
limit_memory_hard   = ${ODOO_LIMIT_MEMORY_HARD}
limit_memory_soft   = ${ODOO_LIMIT_MEMORY_SOFT}
limit_request       = ${ODOO_LIMIT_REQUEST}
limit_time_cpu      = ${ODOO_LIMIT_TIME_CPU}
limit_time_real     = ${ODOO_LIMIT_TIME_REAL}

; === Logging ===
log_level = ${ODOO_LOG_LEVEL}
